apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: epsilon
spec:
  storageClassName: epsilon
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi